// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  ////////////////////////////////////////////////////////////////////////////
  //                                  WEBSITE                               //
  ////////////////////////////////////////////////////////////////////////////
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHJOtE-GLrciYAiGf6mY2pWOy2fVKwKp0',
    appId: '1:912272776985:web:8c4ea1c0acc0e7fa6b2f88',
    messagingSenderId: '912272776985',
    projectId: 'repmobileapp-1a74a',
    authDomain: 'repmobileapp-1a74a.firebaseapp.com',
    databaseURL: 'https://repmobileapp-1a74a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'repmobileapp-1a74a.appspot.com',
    measurementId: 'G-17E5XNXZ41',
  );

  ////////////////////////////////////////////////////////////////////////////
  //                                  ANDROID                               //
  ////////////////////////////////////////////////////////////////////////////
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATyiQwm4qcOpAV3WkYyvEEu_uoAQcfB9I',
    appId: '1:912272776985:android:4130cdac9f84744b6b2f88',
    messagingSenderId: '912272776985',
    projectId: 'repmobileapp-1a74a',
    databaseURL: 'https://repmobileapp-1a74a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'repmobileapp-1a74a.appspot.com',
  );

  ////////////////////////////////////////////////////////////////////////////
  //                                    IOS                                 //
  ////////////////////////////////////////////////////////////////////////////
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkyVt8eIJuzSEVDluMaHcFwrUMpBdDqjY',
    appId: '1:912272776985:ios:2ce190714d33ace26b2f88',
    messagingSenderId: '912272776985',
    projectId: 'repmobileapp-1a74a',
    databaseURL: 'https://repmobileapp-1a74a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'repmobileapp-1a74a.appspot.com',
    iosBundleId: 'com.example.managersDashboard',
  );

  ////////////////////////////////////////////////////////////////////////////
  //                                  MAC OS                                //
  ////////////////////////////////////////////////////////////////////////////
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkyVt8eIJuzSEVDluMaHcFwrUMpBdDqjY',
    appId: '1:912272776985:ios:2ce190714d33ace26b2f88',
    messagingSenderId: '912272776985',
    projectId: 'repmobileapp-1a74a',
    databaseURL: 'https://repmobileapp-1a74a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'repmobileapp-1a74a.appspot.com',
    iosBundleId: 'com.example.managersDashboard',
  );

  ////////////////////////////////////////////////////////////////////////////
  //                                  WINDOWS                               //
  ////////////////////////////////////////////////////////////////////////////
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHJOtE-GLrciYAiGf6mY2pWOy2fVKwKp0',
    appId: '1:912272776985:web:ddc34f48c7bf05c36b2f88',
    messagingSenderId: '912272776985',
    projectId: 'repmobileapp-1a74a',
    authDomain: 'repmobileapp-1a74a.firebaseapp.com',
    databaseURL: 'https://repmobileapp-1a74a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'repmobileapp-1a74a.appspot.com',
    measurementId: 'G-N7VPYEH0SF',
  );
}
